# Generated by Django 5.2.6 on 2025-09-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_vectorstoremeta_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='VectorStoreMeta',
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
