# Generated by Django 5.2.6 on 2025-09-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering'), ('AM', 'Applied Mechanics'), ('ME', 'Mechanical Engineering'), ('HS', 'Humanities and Science (General)'), ('ECE', 'Electronics and Communication Engineering'), ('PE', 'Production Engineering'), ('ICE', 'Instrumentation and Control Engineering')], max_length=50),
        ),
    ]
